version: '3'

services:
  postgres:
    image: 'postgres:14.4-alpine'
    container_name: 'pet-hotel-db'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=pet_db'

  pet-hotel-app:
    build: ./pet-hotel-app
    container_name: 'pet-hotel-app'
    restart: always
    depends_on:
      - postgres
    environment:
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=123'
      - 'DB_URL=jdbc:postgresql://postgres:5432/pet_db'
      - 'PET_SERVICE=pet-service:8081'
      - 'REGISTRATION_SERVICE=registration-service:8082'
      - 'VALIDATION_SERVICE=validation-service:8083'
    ports:
      - "8080:8080"

  pet-service:
    build: ./pet-service
    container_name: 'pet-service'
    restart: always
    depends_on:
      - postgres
    environment:
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=123'
      - 'DB_URL=jdbc:postgresql://postgres:5432/pet_db'

  registration-service:
    build: registration-service
    container_name: 'registration-service'
    restart: always
    depends_on:
      - postgres
    environment:
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=123'
      - 'DB_URL=jdbc:postgresql://postgres:5432/pet_db'

  validation-service:
    build: ./validation-service
    container_name: 'validation-service'
    restart: always
    depends_on:
      - postgres
    environment:
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=123'
      - 'DB_URL=jdbc:postgresql://postgres:5432/pet_db'
